function plotRMSECompare(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  matrix of y data

%  Auto-generated by MATLAB on 18-Oct-2016 11:25:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 4]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,Y1,'MarkerSize',30,'Marker','.','LineStyle','none');
set(plot1(1),'DisplayName','STL','Color',[1 0 0]);
set(plot1(2),'DisplayName','MTASO','Color',[0 0 1]);

% Create line
refline(axes1,1,0);
%line(XData1,XData1,'Parent',axes1);

% Create xlabel
xlabel('RMSE (spMTASO)');

% Create ylabel
ylabel('RMSE (STL,MTASO)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.685488402830033 0.216636347192036 0.184801379067498 0.108695649420437]);

